
name: coverage report

on:
  push:
    branches:
      - master
    paths:
      - "projects/*/src/**/*.spec.ts"

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Install
        run: npm i --ignore-scripts
      - name: test ngx-fake-encapsulation
        run: npm run test:coverage @rautils/ngx-fake-encapsulation || [ 0 -eq 0 ]
      - name: test ngx-image-fallback
        run: npm run test:coverage @rautils/ngx-image-fallback || [ 0 -eq 0 ]
      - name: test ngx-tab-focus
        run: npm run test:coverage @rautils/ngx-tab-focus || [ 0 -eq 0 ]
      - name: codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage/coverage-final.json
          flags: unittests
          name: rautils
