# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: NPM ngx-tab-focus

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install & Build 🔧
        run: npm install && npm run ng build @rautils/ngx-tab-focus --prod
      - name: update NPM package
        with:
          registry-url: https://registry.npmjs.org/
        run: cd dist/ngx-tab-focus && npm publish && cd ../..
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: update Githb Package
        with:
          registry-url: https://npm.pkg.github.com/
        run: npm install && npm run ng build @rautils/ngx-tab-focus --prod && cd dist/ngx-tab-focus && npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
